/**
 * Short weight-gain tips shown beside the score ring on Today. One is picked at random each time
 * the screen opens. Keep each tip to a few words.
 */
export const WEIGHT_GAIN_TIPS = [
  'Add a spoon of peanut butter.',
  'Drink milk instead of water.',
  'Snack on nuts and dried fruit.',
  'Add olive oil to your meals.',
  'Top toast with avocado.',
  'Blend a banana smoothie.',
  'Add cheese to eggs or rice.',
  'Use full-fat yoghurt.',
  'Never skip breakfast.',
  'Eat every 3 hours.',
  'Add an extra egg.',
  'Keep snacks within reach.',
  'Have a bedtime snack.',
  'Add butter or ghee to rice.',
  'Drink juice with meals.',
  "Don't fill up on water first.",
  'Sip drinks after eating.',
  'Use a bigger plate.',
  'Add granola to yoghurt.',
  'Add honey to oats.',
  'Eat bananas daily.',
  'Add a glass of milk at night.',
  'Pick whole milk over skim.',
  'Add paneer or tofu.',
  'Eat dates as a sweet snack.',
  'Sprinkle seeds on everything.',
  'Make oats with milk.',
  'Add a side of potatoes.',
  'Have a handful of trail mix.',
  'Pair fruit with nut butter.',
  'Add coconut milk to curries.',
  'Choose dense breads.',
  'Have a protein shake.',
  'Add an extra roti or slice.',
  'Rest well — sleep builds you up.',
  'Light strength training helps.',
  'Eat slowly, but finish.',
  'Plan meals the night before.',
  'Small, frequent meals add up.',
  'Add hummus to snacks.',
  'Keep a snack in your bag.',
  'Add raisins to cereal.',
  'Spread butter on toast.',
  'Add cream to soups.',
  'Eat rice with every meal.',
  'Try a mango lassi.',
  'Add chickpeas to salads.',
  'Snack on cheese and crackers.',
  'Add nuts to your curry.',
  'Have a milkshake as a treat.',
  'Add an egg to noodles.',
  'Eat a banana before bed.',
  'Add sesame seeds to stir-fries.',
  'Have soup with bread.',
  'Add beans to rice.',
  'Use ghee in dal.',
  'Snack on roasted peanuts.',
  'Try almond butter on apples.',
  'Add chia seeds to smoothies.',
  'Add flaxseed to oats.',
  'Have pancakes for breakfast.',
  'Add peanuts to poha.',
  'Drink a glass of lassi.',
  'Have a boiled egg as a snack.',
  'Add sweet potato to meals.',
  'Eat a second helping.',
  'Add cashews to rice.',
  'Make smoothies with oats.',
  'Add dried figs to snacks.',
  'Put walnuts in yoghurt.',
  'Have muesli with milk.',
  'Add mayo to sandwiches.',
  'Have a cheese toastie.',
  'Add coconut to oats.',
  'Snack on energy balls.',
  'Bake banana bread.',
  'Add pesto to pasta.',
  'Choose pasta for dinner.',
  'Add cheese to pasta.',
  'Have a stuffed paratha.',
  'Add curd to every lunch.',
  'Eat chikki as a snack.',
  'Try peanut chutney.',
  'Add cream to coffee.',
  'Have hot chocolate with milk.',
  'Add an avocado to salads.',
  'Have a fruit and nut bar.',
  'Eat dal with rice daily.',
  'Add sprouts to snacks.',
  'Drink a smoothie daily.',
  'Add a dessert after dinner.',
  'Have kheer or rice pudding.',
  'Snack on makhana.',
  'Add tahini to dressings.',
  'Have a bagel with cream cheese.',
  'Eat salmon or oily fish.',
  'Add chicken to salads.',
  'Have eggs for breakfast.',
  'Add potatoes to curries.',
  'Try a peanut butter sandwich.',
  'Keep nuts by your desk.',
  'Eat even when not hungry.',
  'Set meal reminders.',
  'Eat at the same times daily.',
  "Don't skip lunch.",
  'Eat your snacks — they count!',
  'Add milk powder to shakes.',
  'Add oats to smoothies.',
  'Try overnight oats.',
  'Have a big breakfast.',
  'Make calories easy to drink.',
  'Choose calorie-dense foods.',
  'Prefer dense over bulky foods.',
  'Add sauces and dips.',
  'Have dessert with a smile.',
  'Eat with friends — eat more.',
  'Cook extra and keep leftovers.',
  'Prep snacks for the week.',
  'Walk a bit to build appetite.',
  'Stay consistent, not perfect.',
  'Track progress weekly.',
  'Weigh yourself once a week.',
  'Celebrate small gains.',
  'Lift weights 2–3 times a week.',
  'Squats build healthy weight.',
  'Rest days help you grow.',
  'Manage stress — it cuts appetite.',
  'Sleep 7–9 hours a night.',
  'Limit black coffee before meals.',
  'Every meal is a win.',
] as const

/** A random tip. `random` is injectable for tests and must return a number in [0, 1). */
export function pickTip(random: () => number = Math.random): string {
  const i = Math.min(WEIGHT_GAIN_TIPS.length - 1, Math.floor(random() * WEIGHT_GAIN_TIPS.length))
  return WEIGHT_GAIN_TIPS[i] ?? WEIGHT_GAIN_TIPS[0]
}
